# Generated by Django 5.1.7 on 2025-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commendexecutionhistory',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
