# Generated by Django 5.1.7 on 2026-02-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0002_commendexecutionhistory_is_public'),
        ('common', '0006_clusterlocationnode_cluster_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorIpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.IntegerField(db_index=True, unique=True)),
                ('anchor_name', models.CharField(max_length=512)),
                ('user_anchor_id', models.IntegerField(db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('anchor_location', models.CharField(max_length=255)),
                ('asn', models.CharField(max_length=10)),
                ('isp', models.CharField(max_length=255)),
                ('isp_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anchors_ip_details',
                'indexes': [models.Index(fields=['status'], name='anchors_ip__status_6aed52_idx'), models.Index(fields=['anchor_id'], name='anchors_ip__anchor__f6aee9_idx'), models.Index(fields=['ip_address'], name='anchors_ip__ip_addr_aaac30_idx')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('min_latency', models.FloatField()),
                ('avg_latency', models.FloatField()),
                ('max_latency', models.FloatField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('anchor_ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='anchor.anchoripdetails')),
                ('cluster_ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='common.clusterlocationnode')),
            ],
            options={
                'db_table': 'measurements',
                'indexes': [models.Index(fields=['timestamp'], name='measurement_timesta_133bdb_idx'), models.Index(fields=['anchor_ip_id', 'cluster_ip_id'], name='measurement_anchor__5c4df3_idx')],
            },
        ),
    ]
