# Generated by Django 5.1.7 on 2026-02-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0003_anchoripdetails_measurement'),
        ('common', '0007_alter_clusterlocationnode_cluster_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='command_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='avg_latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='max_latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='min_latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['command_id'], name='measurement_command_aa464f_idx'),
        ),
    ]
