# Generated by Django 5.1.5 on 2025-01-28 16:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=50, null=True)),
                ('package_description', models.CharField(blank=True, max_length=255, null=True)),
                ('package_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('package_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('package_duration', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_default_plan', models.BooleanField(default=False)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package_master',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('used_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('earn_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('remaining_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('package_activation_date', models.DateField(blank=True, null=True)),
                ('package_deactivation_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('insert_status', models.CharField(choices=[('earn', 'earn'), ('spend', 'spend')], default='earn', max_length=100)),
                ('command_name', models.CharField(blank=True, max_length=255, null=True)),
                ('run_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('package', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_id', to='subscription.subscriptionpackagemaster')),
                ('user', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
    ]
