# Generated by Django 5.1.7 on 2025-05-15 09:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('package', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_package_master_id', to='subscription.subscriptionpackagemaster')),
                ('user', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_payment',
            },
        ),
    ]
