"""
Django settings for services_aiori_v2 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from config_env import CONFIG

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jw(%75eu=7&8llf)#of3col9dx53w#30q2y&yi3&+w-ge$h8u('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CONFIG.DEBUG

ALLOWED_HOSTS = CONFIG.ALLOWED_HOST


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',


    'backend.api_app',
    'backend.services_app',
    'backend.users',
    'backend.common',
    'backend.subscription',
    'backend.anchor',
    'corsheaders',
    'django_celery_beat',
    'storages'




]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = CONFIG.CORS_ORIGIN_WHITELIST
# CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



ROOT_URLCONF = 'services_aiori_v2.urls'



# Cache backend
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_DEFAULT_URL,  # Using Redis DB 0 for general caching
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'otp_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_OTP_URL,  # Using Redis DB 1 specifically for OTPs
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'session_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_SESSION_URL,  # Using Redis DB 2 specifically for sessions
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'root_server_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_ROOT_SERVER_URL,  # Using Redis DB 2 specifically for sessions
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'ai_summary_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_AI_SUMMARY_URL,  # Using Redis DB 3 specifically for ai summary
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
    'ip_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': CONFIG.REDIS_IP_URL,  # Using Redis DB 1 specifically for Your IP
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'services_aiori_v2.wsgi.application'


INFLUXDB_HOST = 'https://pingdb.v0.aior.in'
INFLUXDB_DATABASE = 'pingdb'
AIORI_ANCHOR_HOST = 'https://apird3v0.aior.in'
AIORI_ANCHOR_URL = '/apisrv/api/v1/'
AIORI_ANCHOR_GET_RANGE_LIMIT = 10
AIORI_ANCHOR_HOST_URLS_TEST = [
    {
        "server_url": 'https://apird3.aior.in/apisrv/api/v1/',
        "storage_url": 'https://devdb.dev.aior.in',
        "storage_db": 'RtdbSrv',
        "version": 0
    },
    {
        "server_url": 'https://apird3v0.aior.in/apisrv/api/v1/',
        "storage_url": 'https://pingdb.v0.aior.in',
        "storage_db": 'pingdb',
        "version": 1
    }
]
AIORI_ANCHOR_HOST_URLS = [
    {
        "server_url": 'https://apird3v0.aior.in/apisrv/api/v1/',
        "storage_url": 'https://pingdb.v0.aior.in',
        "storage_db": 'pingdb',
        "version": 1
    }
]
AIORI_ANCHOR_SERVER_URLS = 'https://apird3v0.aior.in/apisrv/api/v1/'
# AIORI_ANCHOR_SERVER_URLS = 'https://apird3v0x.aior.in/apisrv/api/v1/'

IPINFO_TOKEN = 'bef5e534ee9caf'
IPINFO_SETTINGS = {
    'cache_options': {
        'ttl':30,
        'maxsize': 128
    },
    # 'countries_file': 'custom_countries.json'
}
IPINFO_FILTER = lambda request: request.scheme == 'http'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
# database credential
DATABASES = {
 
'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': CONFIG.DB_NAME,
        'USER': CONFIG.DB_USER,
        'PASSWORD': CONFIG.DB_PASSWORD,
        'HOST': CONFIG.DB_HOST,
        'PORT': CONFIG.DB_PORT
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Mailtrap email
EMAIL_HOST = CONFIG.EMAIL_HOST
EMAIL_HOST_USER = CONFIG.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = CONFIG.EMAIL_HOST_PASSWORD
EMAIL_PORT = CONFIG.EMAIL_PORT
EMAIL_USE_TLS = CONFIG.EMAIL_USE_TLS
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = CONFIG.DEFAULT_FROM_EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = CONFIG.DEFAULT_FILE_STORAGE

AWS_ACCESS_KEY_ID = CONFIG.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = CONFIG.AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = CONFIG.AWS_STORAGE_BUCKET_NAME
AWS_S3_ENDPOINT_URL = CONFIG.AWS_S3_ENDPOINT_URL
AWS_S3_REGION_NAME = CONFIG.AWS_S3_REGION_NAME
AWS_S3_ADDRESSING_STYLE = CONFIG.AWS_S3_ADDRESSING_STYLE
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'

LOGGING_DIR = Path('/var/log/django')
LOGGING_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(LOGGING_DIR / 'errors.log'),
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',   # captures errors and above
            'propagate': True,
        },
        'boto3': {
            'handlers': ['console'],
            'level': 'DEBUG'
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'DEBUG'
        },
    },
}

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 1   # 1 day

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# Setup JWT Token Variables
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS512',
    'SIGNING_KEY': '8^r39(l%q*fs5hpq)w@&2wratc_rzre)=)2l0zg_3+$%)j**b8',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

CSRF_TRUSTED_ORIGINS = CONFIG.CSRF_TRUSTED_ORIGINS

# ----------------------------------------------------------------
# Celery Configuration
# ----------------------------------------------------------------
CELERY_BROKER_URL = CONFIG.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = CONFIG.CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# ----------------------------------------------------------------
# Celery Beat Schedule
# Replaces APScheduler jobs from backend/anchor/urls.py
# ----------------------------------------------------------------
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'query-history-status-update': {
        'task': 'backend.anchor.tasks.query_history_status_update_task',
        'schedule': 30 * 60,  # every 30 minutes (in seconds)
    },
    'save-anchor-details-from-aiori': {
        'task': 'backend.anchor.tasks.save_anchor_details_from_aiori_task',
        'schedule': 53 * 60,  # every 53 minutes
    },
    'sync-anchor-ip-weekly': {
        'task': 'backend.anchor.tasks.sync_anchor_ip_task',
        'schedule': crontab(hour=2, minute=0, day_of_week='saturday'),
    },
    'sync-pending-measurements-daily': {
        'task': 'backend.anchor.tasks.sync_pending_measurements_task',
        'schedule': crontab(hour=17, minute=0),
    },
    'rd3mn-pin-command-execution': {
        'task': 'backend.anchor.tasks.rd3mn_pin_command_execution_task',
        'schedule': 7 * 60,  # every 7 minutes
    },
    'rd3mn-pin-command-execution-root-server': {
        'task': 'backend.anchor.tasks.rd3mn_pin_command_execution_root_server_task',
        'schedule': crontab(hour=0, minute=30),
    },
    'root-server-pin-result-update': {
        'task': 'backend.anchor.tasks.root_server_pin_result_update_task',
        'schedule': crontab(hour=0, minute=40),
    },
}