# Generated by Django 5.1.5 on 2025-01-28 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citylocation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countries',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country_id', to='common.countries'),
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_country_id', to='common.countries'),
        ),
        migrations.AddField(
            model_name='states',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_state_id', to='common.states'),
        ),
    ]
