# Generated by Django 5.1.5 on 2025-01-29 05:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=250)),
                ('alt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_link', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_type', models.CharField(choices=[('admin', 'admin'), ('frontend', 'frontend')], default='frontend', max_length=20)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('list_orders', models.IntegerField(blank=True, null=True)),
                ('all_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('add_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('edit_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('delete_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('view_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('block_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('import_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('export_action', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active', max_length=50)),
                ('created_by', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_created_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_masters',
            },
        ),
        migrations.CreateModel(
            name='UserGroupMasters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_group_masters',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user_id', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='common.usergroupmasters')),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('edit', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('delete', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('view', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('block', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('import_field', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('export', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_created_by', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_name', to='common.menumasters')),
                ('group', models.ForeignKey(limit_choices_to={'is_deleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='common.usergroupmasters')),
            ],
            options={
                'db_table': 'role_menu_permission',
            },
        ),
    ]
