# Generated by Django 5.1.7 on 2025-05-15 09:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_menumasters_usergroupmasters_usergroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_html', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=255, null=True)),
                ('smoll_content', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='blogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_blog_id', to='common.blogs')),
            ],
            options={
                'db_table': 'blog_comment',
            },
        ),
        migrations.CreateModel(
            name='DefaultSiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_execution_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('commend_execution_ttl', models.CharField(blank=True, max_length=255, null=True)),
                ('rd3mn_server_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rd3mn_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('rd3mn_api_key_value', models.CharField(blank=True, max_length=255, null=True)),
                ('rd3mn_db_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rd3mn_data_storage_db', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'default_site_setup',
            },
        ),
        migrations.CreateModel(
            name='ResearchPageLayouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_parent', models.IntegerField(default=0)),
                ('layout_type', models.IntegerField(default=0)),
                ('template_type', models.CharField(choices=[('info', 'info'), ('graph', 'graph'), ('map', 'map'), ('datatable', 'datatable')], default='info', max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_name', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_function', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_ajax_url', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_coll_no', models.CharField(blank=True, max_length=255, null=True)),
                ('layout_position', models.IntegerField(default=0)),
                ('layout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('created_by', models.ForeignKey(limit_choices_to={'isDeleted': False, 'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_created_by', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_id', to='common.templates')),
            ],
            options={
                'db_table': 'research_page_layouts',
            },
        ),
    ]
