# Generated by Django 5.1.7 on 2026-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_clusterlocationnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterlocationnode',
            name='cluster_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
