# Generated by Django 5.1.7 on 2026-02-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_clusterlocationnode_cluster_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterlocationnode',
            name='cluster_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
