# Generated by Django 5.1.7 on 2025-05-15 06:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussion_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_categories',
            },
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('discussion_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_category_id', to='users.discussioncategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_forum',
            },
        ),
        migrations.CreateModel(
            name='UsersDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_public', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_domain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_domain',
            },
        ),
    ]
