# Generated by Django 5.1.7 on 2025-05-15 07:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_discussioncategories_discussionforum_usersdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersHostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_host_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_host_group',
            },
        ),
        migrations.CreateModel(
            name='UsersHostGroupDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_domain_id', to='users.usersdomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_domain', to=settings.AUTH_USER_MODEL)),
                ('user_host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_host_group_id', to='users.usershostgroup')),
            ],
            options={
                'db_table': 'user_host_group_domain',
            },
        ),
        migrations.CreateModel(
            name='UsersZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_zone_country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_zone_state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_anchor_ids', models.JSONField(blank=True, default=list, null=True)),
                ('user_anchor_names', models.JSONField(blank=True, default=list, null=True)),
                ('user_anchor_latitudes', models.JSONField(blank=True, default=list, null=True)),
                ('user_anchor_longitudes', models.JSONField(blank=True, default=list, null=True)),
                ('user_anchor_locations', models.JSONField(blank=True, default=list, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_zone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_zone',
            },
        ),
        migrations.CreateModel(
            name='UsersZoneAreaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_zone_area', to=settings.AUTH_USER_MODEL)),
                ('user_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_area_id', to='users.userszone')),
            ],
            options={
                'db_table': 'user_zone_area_details',
            },
        ),
    ]
