# Generated by Django 5.1.7 on 2025-05-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usershostgroup_usershostgroupdomain_userszone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
    ]
