# Generated by Django 5.1.7 on 2025-05-19 17:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('uploaded_doc', models.FileField(blank=True, null=True, upload_to='assignment/docs/')),
                ('filename', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('closed', 'Closed')], default='ongoing', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False, 'is_faculty': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='LinkedAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('query_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='users.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False, 'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Assignment',
                'verbose_name_plural': 'Student Assignments',
                'db_table': 'linked_assignment',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['assignment'], name='linked_assi_assignm_b4e6e1_idx'), models.Index(fields=['student'], name='linked_assi_student_df061f_idx')],
            },
        ),
    ]
