# Generated by Django 5.1.7 on 2025-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assignment_linkedassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedassignment',
            name='query_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedassignment',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
