# Generated by Django 5.1.7 on 2025-05-28 16:34

import backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_linkedassignment_query_type_linkedassignment_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_doc',
            field=models.FileField(blank=True, null=True, upload_to=backend.users.models.user_assignment_path),
        ),
    ]
