# Generated by Django 5.1.7 on 2025-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_assignment_uploaded_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hndb_url',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
