# Generated by Django 5.1.7 on 2025-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_reset_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
