# Generated by Django 5.1.7 on 2025-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usersession_isp_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_doc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
