# Generated by Django 5.1.7 on 2025-07-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_assignment_uploaded_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_doc',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
