name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          cd /home/ubuntu/apps/ping

          git fetch origin
          git reset --hard origin/main

          source venv/bin/activate

          pip install -r requirements.txt

          python manage.py migrate

          python manage.py collectstatic --noinput

          sudo systemctl restart gunicorn
          sudo systemctl restart celery-worker
          sudo systemctl restart celery-beat

          echo "Deployment completed successfully."