name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy Docker Application
        shell: bash
        run: |
          set -e

          cd /home/ubuntu/apps/ping

          git fetch origin
          git reset --hard origin/main

          docker compose down

          docker compose up -d --build --remove-orphans

          docker image prune -af

          echo "Deployment completed successfully."